# Лабораторная работа №1
## Выполнил студент группы БСТ1903 Чикенев Станислав Дмитриевич
### Задания №1
1) Создать Jupyter Notebook со следующим наименованием: Lab1_Группа_ФИО

2) Создать новую ячейку с помощью кнопки

3) В созданной ячейке по указанной ниже форме заполните оглавление файла, заменив наименование группы и вписав свое ФИО

4) Форма оглавления файла в ячейке после чего создайте еще одну ячейку и напишите следующий код: "Hello, World!"

5) С помощью кнопки (Run) запустите выполнение всех ячеек.

6) После выполнения у вас должна отформатироваться ячейка с оглавлением и должен выполниться “Hello, World!”

In [36]:
print ("Hello, World!")

Hello, World!


### Задание №2 
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
матрицы, а min_lim и max_lim - минимальное и максимальное значение для
генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
значения:

m = 50

n = 50

min_limit = -250

max_limit = 1000 + (номер своего варианта)

In [37]:
import numpy
import time
def matrixgenerate():
    m = int(input())
    n = int(input())
    min_limit = -250
    max_limit = 1021
    mtr=numpy.random.random_integers(min_limit,max_limit,size=(m,n))
    print ("\nИсходный Массив\n", mtr)
    return mtr
    

                

### Задание №3.1 (Сортировка выбором)
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [38]:
def viborsrt(mtr):
    massive=per(mtr)
    for i in range(len(massive)):
        minn=i
        print(minn)
        for j in range(i,len(massive)):
            if massive[minn]>massive[j]:
                minn=j
        massive[minn], massive[i]=massive[i], massive[minn]
    return rezult(mtr,massive)

### Задание 3.2 (Сортировка вставки)
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [39]:
def vstavka(mtr):
    massive=per(mtr)
    for i in range (1, len(massive)):
        j=i-1
        while (j >= 0) and (massive[j]>massive[j+1]):
            massive[j], massive[j+1]=massive[j+1], massive[j]
            j=j-1
    return rezult (mtr, massive)                    

### Задание 3.3 (Сортировка обменом)
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [40]:
def obmsrt(mtr):
    massive=per(mtr)
    k=len(mtr)
    while k>1:
        for i in range(k-1):
            if massive[i]>massive[i+1]:
                massive[i], massive[i+1]=massive[i+1], massive[i]
            k=k-1
    return rezult (mtr, massive)    

### Задание 3.4 (Сортировка Шелла)
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [41]:
def shella (mtr):
    massive=per(mtr)
    length=len(massive)
    k=length
    while k>0:
        for i in range(length-k):
            j=i
            while j>=0 and massive[j+k]<massive[j]:
                    massive[j], massive[j+k]=massive[j+k],massive[j]
                    j=j-k
        k=int(k/2)
    return rezult(mtr, massive)

### Задание 3.5 (Турнирная сортировка)
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [42]:
def turnirsrt(mtr):
    massivee=per(mtr)
    def turnirrsort01(massive):
        tree = [None] * 2 * (len(massive) + len(massive) % 2)
        index = len(tree) - len(massive) - len(massive) % 2
        for i, v in enumerate(massive):
            tree[index + i] = (i, v)
        for j in range(len(massive)):
            n = len(massive)
            index = len(tree) - len(massive) - len(massive) % 2
            while index > -1:
                n = (n + 1) // 2
                for i in range(n):
                    i = max(index + i * 2, 1)
                    if tree[i] != None and tree[i + 1] != None:
                        if tree[i][1] < tree[i + 1][1]:
                            tree[i // 2] = tree[i]
                        else:
                            tree[i // 2] = tree[i + 1]
                    else:
                        tree[i // 2] = tree[i] if tree[i] != None else tree[i + 1]
                index -= n

            index, x = tree[0]
            massive[j] = x
            tree[len(tree) - len(massive) - len(massive) % 2 + index] = None
    turnirrsort01(massive)
    return rezult(mtr, massive) 

### Задание 3.6 (Быстрая сортировка)
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [47]:
def fast1(mtr):
    massive=per(mtr)
    def forsaj(massive, first, last):
        i=first
        j=last
        x=massive[int((first+last)/2)]
        while i<=j:
            while matrline[i]<x:
                i+=1
            while matrline[j]>x:
                j-=1
            if i<=j:
                if massive[i]>massive[j]:
                    massive[i], massive[j]=massive[j],massive[i]
                i+=1
                j-=1
        if i<last:
            forsaj(massive, i, last)
        if first<j:
            forsaj(massive, first, j)
    forsaj(massive, 0, len(massive)-1)
    return rezult(mtr, massive)

### Задание 3.7 (Пирамидальная сортировка)
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [48]:
def piramid(mtr):
    massive=per(mtr)
    def qwerty(massive, k, n):
        el =massive[k]
        while 2*k+1 < n:
            child = 2*k+1
            if child+1 < n and massive[child] < massive[child+1]:
                child += 1
            if el >= massive[child]:
                break
            massive[k] = massive[child]
            k = child
        massive[k] = el
  
    size = len(massive)
    for i in range(size//2-1,-1,-1):
        qwerty(massive, i, size)
    for i in range(size-1,0,-1):
        temp = massive[i]
        massive[i] = massive[0]
        massive[0] = temp
        qwerty(massive, 0, i)
    return rezult(mtr, massive)

In [49]:
def per(mtr):
    m=len(mtr)
    n=len(mtr[0])
    massive=[0]*(m*n)
    y=int(0)
    for i in range(0, m):
        for j in range(0, n):
            massive[y]=mtr[i][j]
            y=y+1
    return massive

def rezult(mtr, massive):
    m=len(mtr)
    n=len(mtr[0])
    y=int(0)
    matrix=[[0] *n for i in range(m)]
    for i in range(0, m):
        for j in range(0, n):
            mtr[i][j]=massive[y]
            y=y+1
    return mtr

In [50]:
mtr=matrixgenerate()

#Стандартная сортировка
timerStart = time.perf_counter()
massive=per(mtr)
massive=sorted(massive)
matrixstandart=rezult(mtr, massive)
timerEnd = time.perf_counter()
timer1 = timerEnd - timerStart
#

#Сортировка выбором
timerStart = time.perf_counter()
mt1=viborsrt(mtr)
timerEnd = time.perf_counter()
timer2 = timerEnd - timerStart
#

#Сортировка вставками
timerStart = time.perf_counter()
mt2=vstavka(mtr)
timerEnd = time.perf_counter()
timer3 = timerEnd - timerStart
#

#Сортировка обменом
timerStart = time.perf_counter()
mt3=obmsrt(mtr)
timerEnd = time.perf_counter()
timer4 = timerEnd - timerStart
#

#Сортировка Шелла
timerStart = time.perf_counter()
mt4=shella(mtr)
timerEnd = time.perf_counter()
timer5 = timerEnd - timerStart
#

#Турнирная сортировка
timerStart = time.perf_counter()
mt5=turnirsrt(mtr)
timerEnd = time.perf_counter()
timer6 = timerEnd - timerStart
#

#Быстрая сортировка
timerStart = time.perf_counter()
mt6=fast1(mtr)
timerEnd = time.perf_counter()
timer7 = timerEnd - timerStart
#

#Пирамидальная сортировка
timerStart = time.perf_counter()
mt7=piramid(mtr)
timerEnd = time.perf_counter()
timer8 = timerEnd - timerStart
#


print("\nВремя работы стандартной сортировки", timer1,"\nРезультат сортировки\n", *matrixstandart)
print("\nВремя работы сортировки выбором", timer2,"\nРезультат сортировки\n", *mt1)
print("\nВремя работы сортировки вставкой", timer3,"\nРезультат сортировки\n", *mt2)
print("\nВремя работы сортировки обменом", timer4,"\nРезультат сортировки\n", *mt3)
print("\nВремя работы сортировки Шелла", timer5,"\nРезультат сортировки\n", *mt4)
print("\nВремя работы турнирной сортировки", timer6,"\nРезультат сортировки\n", *mt5)
print("\nВремя работы быстрой сортировки", timer7,"\nРезультат сортировки\n", *mt6)
print("\nВремя работы пирамидальной сортировки", timer8,"\nРезультат сортировки\n", *mt7)

4
4

Исходный Массив
 [[  85  818  -47  187]
 [ -59  906  570  552]
 [-117  947 -178   94]
 [ -19  425  628  934]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


<ipython-input-37-2e85a7a97546>:8: DeprecationWarning: This function is deprecated. Please call randint(-250, 1021 + 1) instead
  mtr=numpy.random.random_integers(min_limit,max_limit,size=(m,n))


NameError: name 'matrline' is not defined

In [21]:
 def forsaj(massive, first, last):
        i=first
        j=last
        x=massive[int((first+last)/2)]
        while i<=j:
            print(massive)
            while massive[i]<x:
                i+=1
            while massive[j]>x:
                j-=1
            if i<=j:
                if massive[i]>massive[j]:
                    massive[i], massive[j]=massive[j],massive[i]
                i+=1
                j-=1
        if i<last:
            forsaj(massive, i, last)
        if first<j:
            forsaj(massive, first, j)
        

mas=[9, 4, 3, 2, 1, 5, 7, 6, 8]
forsaj(mas, 0, len(mas)-1)
print(mas)

[9, 4, 3, 2, 1, 5, 7, 6, 8]
[1, 4, 3, 2, 9, 5, 7, 6, 8]
[1, 4, 3, 2, 9, 5, 7, 6, 8]
[1, 4, 3, 2, 8, 5, 7, 6, 9]
[1, 4, 3, 2, 8, 5, 7, 6, 9]
[1, 4, 3, 2, 6, 5, 7, 8, 9]
[1, 4, 3, 2, 6, 5, 7, 8, 9]
[1, 2, 3, 4, 6, 5, 7, 8, 9]
[1, 2, 3, 4, 6, 5, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
