### Задача 1

In [1]:
import numpy

In [2]:
def matrixgenerate():
    n=int(input())
    massiv = numpy.random.random_integers(0, 20, size=(n))
    massiv=sorted(massiv, reverse=True)
    for i, j in enumerate(massiv):
        print("massiv[", i, "]=", j)
    return massiv

In [3]:
def perimetr(massiv):
    P=0
    
    for i in range(len(massiv)-2):
        if massiv[i]<massiv[i+1]+massiv[i+2]:
            return massiv[i]+massiv[i+1]+massiv[i+2]

In [4]:
massiv=matrixgenerate()
# leng=int(input())
# massiv=[0]*leng
# for i in range(len(massiv)):
#    massiv[i]=int(input())
# sorted(massiv)
# for i, j in enumerate(massiv):
#    print("massiv[", i, "]=", j)
P=perimetr(massiv)
print(P)

10
massiv[ 0 ]= 20
massiv[ 1 ]= 17
massiv[ 2 ]= 12
massiv[ 3 ]= 10
massiv[ 4 ]= 7
massiv[ 5 ]= 6
massiv[ 6 ]= 5
massiv[ 7 ]= 5
massiv[ 8 ]= 1
massiv[ 9 ]= 0
49


<ipython-input-2-199a445f327c>:3: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  massiv = numpy.random.random_integers(0, 20, size=(n))


### Задача 2

In [5]:
def check(a,b):
    one=str(a)+str(b)
    two=str(b)+str(a)
    if int(one)>int(two):
        return True
    else:
        return False
    
def shell(massline):
    length=len(massline)
    l=length
    while l>0:
        for i in range(length-l):
            j=i
            while j>=0 and check(massline[j+l], massline[j]):
                massline[j], massline[j+l]=massline[j+l], massline[j]
                j=j-l
        l=int(l/2)
    strr=""
    for i in range(len(massline)):
        strr=strr+" "+str(massline[i])
    return strr

mas1=[9714,9714,971]
mas2=[9999911,91]
mas3=[8,40,24,6,10]
print(shell(mas1))
print(shell(mas2))
print(shell(mas3))

 971 9714 9714
 9999911 91
 8 6 40 24 10


### Задача 3

In [6]:
import numpy

In [7]:
m, n= map(int, input('Введите m и n:').split(' '))
massiv = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i in range(0,m):
    for j in range(0,n):
        l=j
        k=i
        while k<m and l<n:
            if massiv[i][j]>massiv[k][l]:
                print ("заменяет " , massiv[k][l] ," на " , massiv[i][j] )
                massiv[i][j], massiv[k][l]=massiv[k][l], massiv[i][j]
            k=k+1
            l=l+1
print("\n")
print(massiv)

Введите m и n:6 6
[[14 17  4  5 15 12]
 [11  5 11 19  0  4]
 [ 2 13 17 11 15 14]
 [13 18 15 15 12 14]
 [ 9 15 14  2 13 20]
 [10 10  7 17  9 19]]
заменяет  5  на  14
заменяет  11  на  17
заменяет  0  на  5
заменяет  4  на  15
заменяет  2  на  11
заменяет  13  на  14
заменяет  11  на  17
заменяет  15  на  19
заменяет  14  на  15
заменяет  11  на  13
заменяет  9  на  11
заменяет  15  на  17
заменяет  14  на  15
заменяет  12  на  17
заменяет  15  на  19
заменяет  7  на  13
заменяет  14  на  18
заменяет  13  на  15
заменяет  11  на  13
заменяет  15  на  17
заменяет  13  на  15
заменяет  17  на  18
заменяет  13  на  15


[[ 5 11  4  0  4 12]
 [ 2 13 11 14  5 15]
 [ 2  9 14 12 15 14]
 [ 7 14 11 15 17 19]
 [ 9 13 17 13 17 20]
 [10 10 15 18 15 19]]


<ipython-input-7-ec6d2022ab5b>:2: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  massiv = numpy.random.random_integers(0, 20, size=(m, n))
