# Курсовая работа по дисциплине СиАОД №1¶
# Выполнил студент группы БСТ1903 Чикенев Станислав


## Задача 1 «Треугольник с максимальным периметром»

Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью ­ функция возвращает 0.

In [2]:
#Находжение периметра
def Perimetr (a, b, c):
    if (a+b)>c and (a+c)>b and (b+c)>a:
        return int(a+b+c)
    else:
        return 0
#
length=int(input('Введите длину массива'))
mas=[]
for i in range(length):
    mas.append(int(input()))
mas=sorted(mas, reverse=True)
print(mas)
for i in range(len(mas)-2):
    if Perimetr(mas[i], mas[i+1], mas[i+2])>0:
        print("Периметр=", Perimetr(mas[i], mas[i+1], mas[i+2]))
        break


Введите длину массива6
1
2
3
4
5
6
[6, 5, 4, 3, 2, 1]
Периметр= 15


## Задача 2. «Максимальное число»

Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число.

In [3]:
def check(a,b):
    one=str(a)+str(b)
    two=str(b)+str(a)
    if int(one)>int(two):
        return True
    else:
        return False
    
def shell(massline):
    length=len(massline)
    l=length
    while l>0:
        for i in range(length-l):
            j=i
            while j>=0 and check(massline[j+l], massline[j]):
                massline[j], massline[j+l]=massline[j+l], massline[j]
                j=j-l
        l=int(l/2)
    strr=""
    for i in range(len(massline)):
        strr=strr+" "+str(massline[i])
    return strr1

mas1=[8308,8308,830]
mas2=[99991,9]
mas3=[3,30,34,5,9]
print(shell(mas1))
print(shell(mas2))
print(shell(mas3))

 8308 8308 830
 9 99991
 9 5 34 3 30


Дана матрица mat размером m * n, значения ­ целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [21]:
import numpy
m, n= map(int, input('Введите m и n:').split(' '))
massiv = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i in range(0,m):
    for j in range(0,n):
        l=j
        k=i
        while k<m and l<n:
            if massiv[i][j]>massiv[k][l]:
                print ("заменяет " , massiv[k][l] ," на " , massiv[i][j] )
                massiv[i][j], massiv[k][l]=massiv[k][l], massiv[i][j]
            k=k+1
            l=l+1
print("\n")
print(massiv)

Введите m и n:4 4
[[ 0  8  2 14]
 [ 7  6  0 18]
 [15  2  6 20]
 [10  8  6  8]]
заменяет  0  на  8
заменяет  2  на  7
заменяет  8  на  15
заменяет  6  на  7


[[ 0  0  2 14]
 [ 2  6  8 18]
 [ 8  6  6 20]
 [10 15  7  8]]


<ipython-input-21-5a0ebf00e0be>:3: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  massiv = numpy.random.random_integers(0, 20, size=(m, n))


## Задача 4 «Шарики и стрелы»

Некоторые сферические шарики распределены по двухмерному пространству. Для каждого шарика даны xкоординаты начала и конца его горизонтального диаметра. Так как пространство двумерно, то yкоординаты не имеют значения в данной задаче. Координата xstart всегда меньше xend. Стрелу можно выстрелить строго вертикально (вдоль yоси) из разных точек xоси. Шарик с координатами xstart и xend уничтожается стрелой, если она была выпущена из такой позиции x, что xstart ⩽ x ⩽ xend. Когда стрела выпущена, она летит в пространстве бесконечное время (уничтожая все шарики на пути). Дан массив points, где points[i] = [xstart, xend]. Напишите функцию, возвращающую минимальное количество стрел, которые нужно выпустить, чтобы уничтожить все шарики.

In [22]:
class sh:
    def __init__(self, mass):
        self.mass=mass
        self.count=1
    
    def search(self):
        if len(self.mass)==0:
            self.count=0
        else:
            m=0
            for i in range(len(self.mass)):
                self.mass.sort()
            print(self.mass)
            for i in range(len(self.mass)-1):
                if self.mass[m][1]<self.mass[i+1][0]:
                    self.count=self.count+1
                    m=i+1
                elif self.mass[m][0]<=self.mass[i+1][0] and self.mass[m][1]>=self.mass[i+1][1]:
                       m=i+1
                    
        return self.count
            
mass=[[9,12],[1,10],[4,11],[8,12],[3,9],[6,9],[6,7]]           
a=sh(mass)
print(a.search())

[[1, 10], [3, 9], [4, 11], [6, 7], [6, 9], [8, 12], [9, 12]]
2


## Задача 5 «Стопки монет»

На столе стоят 3n стопок монет. Вы и ваши друзья Алиса и Боб забираете стопки монет по следующему алгоритму:

Вы выбираете 3 стопки монет из оставшихся на столе. Алиса забирает себе стопку с максимальным количеством монет. Вы забираете одну из двух оставшихся стопок. Боб забирает последнюю стопку. Если еще остались стопки, то действия повторяются с первого шага. Дан массив целых положительных чисел piles. Напишите функцию, возвращающую максимальное число монет, которое вы можете получить.

In [23]:
def moneti(arr):
    arr.sort()
    a=len(arr)//3
    s=0
    while a<len(arr):
        s=s+arr[a]
        a=a+2
    return (s)
moneti ( [9,8,7,6,5,1,2,3,4])

18

## Задача 6 «Объединение отрезков»

Дан массив отрезков intervals, в котором intervals[i] = [start_i, end_i], некоторые отрезки могут пересекаться. Напишите функцию, которая объединяет все пересекающиеся отрезки в один и возвращает новый массив непересекающихся отрезков.



In [24]:
def comb_otr(interv):
    interv.sort()
    i=0
    while i <len(interv)-1:
        if interv[i][1]>=interv[i+1][0]:
            a=interv.pop(0)
            b=interv.pop(0)
            interv.insert(0, [a[0],b[1]])
        else:
            i+=1            
    return interv

comb_otr( [[1,4],[4,5]])

[[1, 5]]

## Задача 7

Даны две строки: s1 и s2 с одинаковым размером, проверьте, может ли некоторая перестановка строки s1 “победить” некоторую перестановку строки s2 или наоборот. Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y [i] (в алфавитном порядке) для всех i от 0 до n-1.

In [25]:
def zadacha_7(str1, str2):
    if len(str1)!=len(str2):
        return False
    st1=list(str1)
    st2=list(str2)
    l=len(st1)
    st1.sort()
    st2.sort()
    i=0
    while i<l and st1[i]==st2[i]:
        i+=1
    if i == l:
        return True
    if st1[i]>st2[i]:
        for k in range(len(st1)):
            if(st1[k]<st2[k]):
                return False
        return True
    else:
        for k in range(len(st2)):
            if(st2[k]<st1[k]):
                return False
        return True
            
    
zadacha_7('abe','acb')

True

## Задача 8

Дана строка s, вернуть самую длинную полиндромную подстроку в s.

In [28]:
def palindrome(str1):
    maxstr=''
    for i in range(len(str1)-1):
        for j in range(i+1, len(str1)):
            if str1[i:j+1]==str1[i:j+1][::-1] and len(maxstr)<len(str1[i:j+1]):
                maxstr=str1[i:j+1]
    return maxstr

timerStart = time.perf_counter()             
print(palindrome("капролодкакпопнонj"))
timerEnd = time.perf_counter()
timer1 = timerEnd - timerStart
print(timer1)

оло
0.00027699999998276326


## Задача 9

Вернуть количество отдельных непустых подстрок текста, которые могут быть записаны как конкатенация некоторой строки с самой собой (т.е. она может быть записана, как a + a, где a - некоторая строка).

In [4]:
import time
def len_podstr(str1):
    rez=set()
    for i in range(len(str1)-1):
        k=i
        for j in range(i+1, len(str1)):
            #print(str1[i:j],str1[j:j+(j-i)])
            if j+(j-i)+1<len(str1) and str1[i:j]==str1[j:j+(j-i)]:
                print(str1[i:j],str1[j:j+(j-i)])
                rez.add(str1[i:j+(j-i)])
                         
    return rez, len(rez)

timerStart = time.perf_counter() 
print (len_podstr("абвгддгвпопомткотокшру") )
timerEnd = time.perf_counter()
timer1 = timerEnd - timerStart
print(timer1)

д д
по по
({'дд', 'попо'}, 2)
0.000792100000580831


# Вывод:

В ходе проделанной работы были выполнены задачи на нахождение максимального периметра, максимального числа, сортировки диагоналей, 3 задачи по работе со строками, монетки, интервалы а также шарики и стрелы